<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Console' => $vendorDir . '/symfony/console/',
    'Nella\\Doctrine' => $vendorDir . '/nella/doctrine/./',
    'Nella\\Console' => $vendorDir . '/nella/console/./',
    'Doctrine\\ORM' => $vendorDir . '/doctrine/orm/lib/',
    'Doctrine\\DBAL\\Migrations' => $vendorDir . '/doctrine/migrations/lib',
    'Doctrine\\DBAL' => $vendorDir . '/doctrine/dbal/lib/',
    'Doctrine\\Common' => $vendorDir . '/doctrine/common/lib/',
);
